################################################################################
# Build
# - La tâche build:dev est exécutée pour pouvoir joué les tests sauf sur les tags.
# - La tâche build:prod est exécutée uniquement pour initialiser la prod et pour les tags.
################################################################################

build:
    stage: build
    rules:
        - if: '$CI_COMMIT_REF_NAME =~ /^develop$/'
          when: manual
        - if: '$CI_COMMIT_TAG !~ "/^$/"'
          when: always
        - when: never
    script:
        - composer install --no-interaction --no-dev --optimize-autoloader
        - npm install
        - gulp build
        - rm -f web/core/install.php
    artifacts:
        paths:
            - .eslintrc.json
            - .stylelintrc.json
            - node_modules
            - vendor
            - web
        expire_in: 1 day
